server:
  port: 6010
  servlet:
    context-path: /hz_apps
report_idcard:
  idcard_url: http://opentest.ihaozhuo.com:20002/getInfoByHealthReportIds
spring:
  profiles:
    active: dev
#  data:
#    elasticsearch:
#      cluster-name: hz-datag-es
#      cluster-nodes: 192.168.20.153:9300
  datasource:
    Url: jdbc:mysql://106.52.120.217:3306/hz_dev?useUnicode=true&characterEncoding=utf-8
    username: root
    password: GUO;chuang.123
#    jdbcUrl: jdbc:mysql://192.168.1.201:3306/rule?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: mysql4hz@2015
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true