server:
  port: 6012
  servlet:
    context-path: /hz_apps
report_idcard:
  idcard_url: http://192.168.10.156/getInfoByHealthReportIds
spring:
  profiles:
    active: pro
#  data:
#    elasticsearch:
#      cluster-name: hz-datag-es
#      cluster-nodes: 192.168.20.153:9300
  datasource:
    name: datasource
    Url: jdbc:mysql://rm-uf64qwlstnkq2n35u.mysql.rds.aliyuncs.com:3306/bisys?useUnicode=true&characterEncoding=utf-8
    username: datag
    password: yjkdatag
    driver-class-name: com.mysql.cj.jdbc.Driver
#    jdbcUrl: jdbc:mysql://192.168.1.201:3306/rule?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: mysql4hz@2015
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true